### ISSUE TITLE
Darkmode issue

### ISSUE THREAD

**Issue by KevinNitroG** [longtoZ/score#1]
1. Khi bật darkmode, lúc chuyển trang thì web phải chuyển từ light mode sang darkmode gây ra hiện tượng nháy sáng.
2. Khi bật darkmode, ấn tắt lần 1 không được _(có lẽ web hiểu nhầm là bật darkmode)_

**Comment by longtoZ** [comment]
Recently I have no idea haha! Maybe later

**Comment by KevinNitroG** [comment]
Later of later of the later

**Comment by longtoZ** [comment]
> Later of later of the later

Do pull request and I'll merge it to main branch (if it works lol)

**Comment by longtoZ** [comment]
Fixed!
